In [ ]:
#create npz

In [ ]:
#read bbx in text file into numpy array

import numpy as np
from os.path import join  
import re

for i in range(500):#(1000):
    bbx_list=[]    
    f = open("/home/meiyih/Challenge4_Test_Task1_GT/gt_img_"+str(i+1)+".txt", "r")#("/home/meiyih/ch4_training_localization_transcription_gt/gt_img_"+str(i+1)+".txt", "r")
    save_path = join('/home/meiyih/test_bbx/', str(i+1))
    for line in f:
        # each line has one ploygen (4 vetices), and others.
        # e.g., 695,885,866,888,867,1146,696,1143,Latin,9
        line = line.strip()
        strs = line.split(',')
        upper_left_x=[int(re.sub("[^0-9]", "", (line.split(',')[0])))]#Upper left x coordinate
        xy = [int(x) for x in strs[1:8]]
        xy = upper_left_x + xy
        xs = xy[0::2]#start from index 0, skip 1 value
        ys = xy[1::2]#start from index 1, skip 1 value
        bbox = [min(xs), min(ys), max(xs), max(ys)]
        bbx_list.append([min(xs), min(ys), max(xs), max(ys)])
    pred_bbox = np.array(bbx_list)
    pred_scores = np.ones(len(bbx_list))
    np.savez(save_path, bbox = pred_bbox, scores = pred_scores)

In [ ]:
#read bbx in text file into numpy array

import numpy as np
from os.path import join  
import re

for i in range(1000):#(500):
    bbx_list=[]    
    f = open("/home/meiyih/ch4_training_localization_transcription_gt/gt_img_"+str(i+1)+".txt", "r")#("/home/meiyih/Challenge4_Test_Task1_GT/gt_img_"+str(i+1)+".txt", "r")
    save_path = join('/home/meiyih/text_icdar_bbx/', str(i+1))
#     for line in f:
#         # each line has one ploygen (4 vetices), and others.
#         # e.g., 695,885,866,888,867,1146,696,1143,Latin,9
#         line = line.strip()
#         print('line : ',line)
#         strs = line.split(',')
#         print('strs : ',strs)
#         upper_left_x=[int(re.sub("[^0-9]", "", (line.split(',')[0])))]#Upper left x coordinate
#         xy = [int(x) for x in strs[1:8]]
#         xy = upper_left_x + xy
#         print('xy : ',xy)
#         xs = xy[0::2]#start from index 0, skip 1 value
#         print('xs : ',xs)
#         ys = xy[1::2]#start from index 1, skip 1 value
#         print('ys : ',ys)
#         bbox = [min(xs), min(ys), max(xs), max(ys)]
#         print('bbox : ',bbox)
        
    for x in f:#read every lines in the txt file
        #if (x.split(',')[-1]) != "###\n":
        x1=int(re.sub("[^0-9]", "", (x.split(',')[0])))#Upper left x coordinate 
        #print(type(x1))
        y1=int(x.split(',')[1])#upper left y coordinate
        x2=int(x.split(',')[4])#lower right x coordinate
        y2=int(x.split(',')[5])#lower right y coordinate
        bbx_list.append([x1,y1,x2,y2])
    pred_bbox = np.array(bbx_list)
    pred_scores = np.ones(len(bbx_list))
    np.savez(save_path, bbox = pred_bbox, scores = pred_scores)

In [9]:
npzfile=np.load('/home/meiyih/InstColorization/test_data/test_bbx/143.npz')#/content/InstColorization/example_bbox/000000022969.npz')
print(npzfile.files)
npzfile['bbox'],npzfile['scores']

['bbox', 'scores']


(array([[ 617,  388,  649,  443],
        [ 650,  394,  699,  456],
        [ 841,  352, 1030,  480],
        [1025,  388, 1250,  490],
        [ 841,  451, 1276,  718],
        [ 471,  372,  504,  434],
        [ 441,  413,  471,  452]]),
 array([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
for line in gt_list:
        # each line has one ploygen (4 vetices), and others.
        # e.g., 695,885,866,888,867,1146,696,1143,Latin,9
        line = line.strip()
        strs = line.split(',')
        xy = [int(x) for x in strs[0:8]]
        xs = xy[0::2]#start from index 0, skip 1 value
        ys = xy[1::2]#start from index 1, skip 1 value

        bbox = [min(xs), min(ys), max(xs), max(ys)]

In [4]:
from PIL import Image, ImageDraw
import glob 
import cv2


for filename in glob.iglob('/home/meiyih/A/'+"*"+'.png'):
    print(filename)
    im = cv2.imread(filename)
    img_name=filename.split('/')[-1]
    im = cv2.resize(im, (512, 512))
    cv2.imwrite(f'/home/meiyih/B/'+img_name,im)


/home/meiyih/A/00042_00_0.1s.png
/home/meiyih/A/00039_00_0.04s.png
/home/meiyih/A/00004_00_10s.png
/home/meiyih/A/00009_00_10s.png
/home/meiyih/A/00012_00_10s.png
/home/meiyih/A/00041_00_0.1s.png
/home/meiyih/A/00010_00_10s.png
/home/meiyih/A/00001_00_0.1s.png
/home/meiyih/A/00041_00_0.04s.png
/home/meiyih/A/00001_00_10s.png
/home/meiyih/A/00002_00_10s.png
/home/meiyih/A/00042_00_0.04s.png
/home/meiyih/A/00013_00_10s.png
/home/meiyih/A/00014_00_10s.png


In [20]:
from PIL import Image, ImageDraw
import glob 
import cv2
import numpy as np
im = cv2.imread('/home/meiyih/masks/img_1.jpg', cv2.IMREAD_GRAYSCALE)
_, im = cv2.threshold(im, 127, 255, cv2.THRESH_BINARY)
im_div=np.expand_dims(np.expand_dims(np.float32(im/ 255.0), axis=2), axis=0)
np.unique(im_div)

array([0., 1.], dtype=float32)

In [19]:
from PIL import Image, ImageDraw
import glob 
import cv2
import numpy as np
im = cv2.imread('/home/meiyih/edge_en/1.png', cv2.IMREAD_GRAYSCALE)
im=np.expand_dims(np.expand_dims(np.float32(im/ 255.0), axis=2), axis=0)
np.unique(im)

array([0.        , 0.00392157, 0.00784314, 0.01176471, 0.01568628,
       0.01960784, 0.02352941, 0.02745098, 0.03137255, 0.03529412,
       0.03921569, 0.04313726, 0.04705882, 0.05098039, 0.05490196,
       0.05882353, 0.0627451 , 0.06666667, 0.07058824, 0.07450981,
       0.07843138, 0.08235294, 0.08627451, 0.09019608, 0.09411765,
       0.09803922, 0.10196079, 0.10588235, 0.10980392, 0.11372549,
       0.11764706, 0.12156863, 0.1254902 , 0.12941177, 0.13333334,
       0.13725491, 0.14117648, 0.14509805, 0.14901961, 0.15294118,
       0.15686275, 0.16078432, 0.16470589, 0.16862746, 0.17254902,
       0.1764706 , 0.18039216, 0.18431373, 0.1882353 , 0.19215687,
       0.19607843, 0.2       , 0.20392157, 0.20784314, 0.21176471,
       0.21568628, 0.21960784, 0.22352941, 0.22745098, 0.23137255,
       0.23529412, 0.23921569, 0.24313726, 0.24705882, 0.2509804 ,
       0.25490198, 0.25882354, 0.2627451 , 0.26666668, 0.27058825,
       0.27450982, 0.2784314 , 0.28235295, 0.28627452, 0.29019

In [6]:
from PIL import Image, ImageDraw
import glob 



for filename in glob.iglob('/home/meiyih/ch4_training_images/'+"*"+'.jpg'):
    print(filename)
    img = Image.open(filename)
    new = Image.new("1", img.size)#create new binary image of img size
    idraw = ImageDraw.Draw(new)#to draw rectangles onto the newly created 
    
    
    f = open("/home/meiyih/ch4_training_localization_transcription_gt/gt_"+((filename.split('/')[-1]).split('.')[0])+".txt", "r")
    for x in f:#read every lines in the txt file
        #if (x.split(',')[-1]) != "###\n":
        x1=int(re.sub("[^0-9]", "", (x.split(',')[0])))#Upper left x coordinate 
        #print(type(x1))
        y1=int(x.split(',')[1])#upper left y coordinate
        x2=int(x.split(',')[4])#lower right x coordinate
        y2=int(x.split(',')[5])#lower right y coordinate
        idraw.rectangle((x1,y1,x2,y2), fill=1)
        #new.show()
        new.save('/home/meiyih/ch4_training_binary_gt/'+((filename.split('/')[-1]).split('.')[0])+'.jpg')
#         else:
#             new.save('/home/meiyih/ch4_training_binary_gt/'+((filename.split('/')[-1]).split('.')[0])+'.jpg')

/home/meiyih/ch4_training_images/img_619.jpg
/home/meiyih/ch4_training_images/img_921.jpg
/home/meiyih/ch4_training_images/img_292.jpg
/home/meiyih/ch4_training_images/img_171.jpg
/home/meiyih/ch4_training_images/img_862.jpg
/home/meiyih/ch4_training_images/img_626.jpg
/home/meiyih/ch4_training_images/img_573.jpg
/home/meiyih/ch4_training_images/img_695.jpg
/home/meiyih/ch4_training_images/img_865.jpg
/home/meiyih/ch4_training_images/img_959.jpg
/home/meiyih/ch4_training_images/img_63.jpg
/home/meiyih/ch4_training_images/img_417.jpg
/home/meiyih/ch4_training_images/img_797.jpg
/home/meiyih/ch4_training_images/img_65.jpg
/home/meiyih/ch4_training_images/img_623.jpg
/home/meiyih/ch4_training_images/img_145.jpg
/home/meiyih/ch4_training_images/img_151.jpg
/home/meiyih/ch4_training_images/img_149.jpg
/home/meiyih/ch4_training_images/img_316.jpg
/home/meiyih/ch4_training_images/img_46.jpg
/home/meiyih/ch4_training_images/img_740.jpg
/home/meiyih/ch4_training_images/img_283.jpg
/home/meiyih/

In [ ]:
from PIL import Image, ImageDraw
import glob 
import re


for filename in glob.iglob('/home/meiyih/low/'+"*"+'.jpg'):
    print(filename)
    img = Image.open(filename)
    new = Image.new("1", img.size)#create new binary image of img size
    idraw = ImageDraw.Draw(new)#to draw rectangles onto the newly created 
    
    
    f = open("/home/meiyih/gt/gt_img_"+((filename.split('/')[-1]).split('.')[0])+".txt", "r")
    for x in f:#read every lines in the txt file
        x1=int(re.sub("[^0-9]", "", (x.split(',')[0])))#Upper left x coordinate 
        print((x1))
        y1=int(x.split(',')[1])#upper left y coordinate
        x2=int(x.split(',')[4])#lower right x coordinate
        y2=int(x.split(',')[5])#lower right y coordinate
        idraw.rectangle((x1,y1,x2,y2), fill=1)
        new.show()
        new.save('/home/meiyih/mask_with_all_text/'+((filename.split('/')[-1]).split('.')[0])+'.jpg')
        break

#  Enhance 25 times


In [1]:

from PIL import Image, ImageEnhance
import glob 

ratio_img_name=[]

#i=0
#read the image 
for filename in glob.iglob('/home/meiyih/howards_test_low/'+"*"+'.jpg'):
    im = Image.open(filename)
#     print(filename)
    #image brightness enhancer
    enhancer = ImageEnhance.Brightness(im)
 
    factor = 25 #brightens the image
    print(factor)
    # to reduce brightness by 50%, use factor 0.5
    im_output = enhancer.enhance(factor)
    #ratio_img_name.append(str(factor)+","+filename)
    im_output.save('/home/meiyih/howards_test_low_brighten25/'+filename.split("/")[-1])
    #i+=1
    


25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
2

# Reduce Brightness


In [4]:
import random

ratio_list = []
random.seed(10)
for i in range(1000):
    x = random.uniform(0.2,0.3)#(0.01,0.1)
    ratio_list.append(x)

print(len(ratio_list))
print(type(ratio_list[0]))

1000
<class 'float'>


In [5]:


from PIL import Image, ImageEnhance
import glob 

ratio_img_name=[]

i=0
#read the image 
for filename in glob.iglob('/home/meiyih/ch4_test_images/'+"*"+'.jpg'):
    im = Image.open(filename)
#     print(filename)
    #image brightness enhancer
    enhancer = ImageEnhance.Brightness(im)
 
    factor = ratio_list[i] #darkens the image
    print(factor)
    # to reduce brightness by 50%, use factor 0.5
    im_output = enhancer.enhance(factor)
    ratio_img_name.append(str(factor)+","+filename)
    im_output.save('/home/meiyih/ch4_test_rand_0.2-0.3/'+filename.split("/")[-1])
    i+=1
    


0.25714025946899133
0.24288890546751146
0.257809130113447
0.22060982321395017
0.281332125135732
0.28235888725334457
0.26534725339011755
0.21602295565188198
0.25206693596399243
0.2327772811622093
0.22499966766864005
0.29528169091459117
0.29965569925394553
0.20445563824504331
0.28601610372862907
0.2603190610968185
0.2381605985919118
0.22836182179067152
0.2674964847134956
0.24568311510583057
0.26858614854745944
0.2661846320052351
0.2132978144712213
0.2767837813943991
0.2982413249011191
0.2969388160404919
0.26133268205467086
0.2044260632864621
0.20040551441584076
0.2133972527049134
0.2941002271395834
0.23028605620290724
0.23661456016604265
0.28981962445391884
0.23143638049564508
0.25489821840124055
0.24360309576241224
0.20649941761268506
0.258454622570193
0.2844067897661902
0.21564189183874066
0.22242989686860415
0.24128702077148406
0.20369248690586292
0.2496603498616548
0.2817982864429632
0.2657890938759109
0.25334837356527723
0.28551257407735997
0.21496881349714017
0.2567235476863124
0.2

In [26]:
with open('ch4_train_rand_0.9-1.0.txt', 'a') as f:
    f.writelines("%s\n" % l for l in ratio_img_name)

In [4]:
#reduce all by 0.04
from PIL import Image, ImageEnhance
import glob 

#read the image 
for filename in glob.iglob('/home/meiyih/ch4_training_images/'+"*"+'.jpg'):
    im = Image.open(filename)
    
    #image brightness enhancer
    enhancer = ImageEnhance.Brightness(im)
 
    factor = 0.04
    # to reduce brightness by 50%, use factor 0.5
    im_output = enhancer.enhance(factor)
    im_output.save('/home/meiyih/ch4_0.04_low_light_training_images/'+filename.split("/")[-1])
    
    


In [25]:
from PIL import Image, ImageEnhance
import glob 
import numpy as np
for filename in glob.iglob('/home/meiyih/'+"*"+'.gif'):
    print(filename)
    im = np.array( Image.open(filename))
    print(im)
    print("Labels in the mask thresholded are : ", np.unique(im).shape)
    print("Labels in the mask thresholded are : ", type(np.unique(im)[0]))

/home/meiyih/0cdf5b5d0ce1_04_mask.gif
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Labels in the mask thresholded are :  (2,)
Labels in the mask thresholded are :  <class 'numpy.uint8'>


In [24]:
from PIL import Image, ImageEnhance
import glob 
import numpy as np
for filename in glob.iglob('/home/meiyih/'+"*"+'.jpg'):
    print(filename)
    im = np.array( Image.open(filename))#
    print(im.shape)
    im = np.where(im >128, 1, 0)
    print("Labels in the mask thresholded are : ", np.unique(im))
    print("Labels in the mask thresholded are : ", np.unique(im).shape)
    print("Labels in the mask thresholded are : ", type(np.unique(im)[0]))
    print(im.shape)
    
#     img.save('/home/meiyih/ch4_training_binary_gt_1_0/'+((filename.split('/')[-1]).split('.')[0])+'.jpg')

/home/meiyih/0cdf5b5d0ce1_08.jpg
(1280, 1918, 3)
Labels in the mask thresholded are :  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 

In [ ]:
/home/meiyih/0cdf5b5d0ce1_04_mask.gif
(1280, 1918)
Labels in the mask thresholded are :  [0 1]
Labels in the mask thresholded are :  (2,)
Labels in the mask thresholded are :  <class 'numpy.uint8'>
(1280, 1918)

# resize 512 x 512 back to original size

In [27]:
#resize 512 x 512 back to original size
import glob
from PIL import Image 
import PIL 
for file in glob.glob('/home/meiyih/Pytorch-UNet_run1/run_pred/'+"*.png"):
    print(file.split('/')[-1].split('.')[0])
    pil_img = Image.open(file)
    pil_img = pil_img.resize((1280, 720), resample= Image.BICUBIC)
    pil_img.save('/home/meiyih/Pytorch-UNet_run1/resize_rgb_pred/'+(file.split('/')[-1].split('.')[0])+".png")

RGB_pred_64
RGB_pred_79
RGB_pred_4
RGB_pred_97
RGB_pred_27
RGB_pred_65
RGB_pred_1
RGB_pred_20
RGB_pred_9
RGB_pred_59
RGB_pred_29
RGB_pred_83
RGB_pred_23
RGB_pred_86
RGB_pred_2
RGB_pred_98
RGB_pred_33
RGB_pred_24
RGB_pred_34
RGB_pred_84
RGB_pred_40
RGB_pred_94
RGB_pred_51
RGB_pred_58
RGB_pred_82
RGB_pred_63
RGB_pred_92
RGB_pred_85
RGB_pred_55
RGB_pred_54
RGB_pred_99
RGB_pred_49
RGB_pred_28
RGB_pred_52
RGB_pred_88
RGB_pred_15
RGB_pred_90
RGB_pred_89
RGB_pred_61
RGB_pred_19
RGB_pred_14
RGB_pred_5
RGB_pred_32
RGB_pred_81
RGB_pred_36
RGB_pred_45
RGB_pred_74
RGB_pred_72
RGB_pred_60
RGB_pred_12
RGB_pred_76
RGB_pred_26
RGB_pred_35
RGB_pred_73
RGB_pred_42
RGB_pred_96
RGB_pred_70
RGB_pred_18
RGB_pred_7
RGB_pred_16
RGB_pred_62
RGB_pred_87
RGB_pred_69
RGB_pred_43
RGB_pred_78
RGB_pred_44
RGB_pred_6
RGB_pred_50
RGB_pred_80
RGB_pred_39
RGB_pred_93
RGB_pred_30
RGB_pred_67
RGB_pred_71
RGB_pred_66
RGB_pred_48
RGB_pred_68
RGB_pred_17
RGB_pred_31
RGB_pred_10
RGB_pred_91
RGB_pred_46
RGB_pred_3
RGB_pred_75


In [ ]:
import glob
from PIL import Image 
import PIL 

def main():
    print('run')
    for file in glob.glob('/media/meiyih/meiyih_datasets/Pytorch-UNet_run2/run_pred/'+"*.png"):
        print(file.split('/')[-1].split('.')[0])
        pil_img = Image.open(file)
        pil_img = pil_img.resize((1280, 720), resample= Image.BICUBIC)
        pil_img.save('/media/meiyih/meiyih_datasets/Pytorch-UNet_run2/resize_rgb_pred/'+(file.split('/')[-1].split('.')[0])+".png")
        
        
        
if __name__ == "__main__":
    main()



In [29]:
!git clone https://github.com/clovaai/CRAFT-pytorch.git

Cloning into 'CRAFT-pytorch'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 59 (delta 0), reused 0 (delta 0), pack-reused 56
Unpacking objects: 100% (59/59), 1.69 MiB | 12.27 MiB/s, done.


In [31]:
import os
os.chdir('/home/meiyih/Pytorch-UNet_run1/CRAFT-pytorch')
!python test.py --trained_model='/media/meiyih/meiyih_datasets/Pytorch-UNet_run2/craft_ic15_20k.pth' --test_folder='/home/meiyih/Pytorch-UNet_run1/resize_rgb_pred'

Loading weights from checkpoint (/media/meiyih/meiyih_datasets/Pytorch-UNet_run2/craft_ic15_20k.pth)
elapsed time : 16.669294834136963sytorch-UNet_run1/resize_rgb_pred/RGB_pred_25.png


# move file to another folder


In [ ]:
import shutil
import os

source = "/home/meiyih/Pytorch-UNet_run1/ch4_low_light_test_images_mix_with_inference_output"
destination = "/home/meiyih/Pytorch-UNet_run1/inference_output"

files = os.listdir(source)

for file in files:
    if "OUT" in file:
        new_path = shutil.move(f"{source}/{file}", destination)
        print(new_path)



# Compute psnr


In [25]:
from __future__ import division
import os, scipy.io, scipy.misc, cv2
import numpy as np
import glob
import math
from skimage.metrics import peak_signal_noise_ratio
from skimage.metrics import structural_similarity

gt_dir = './ch4_test_images/'

psnrs, ssims = [], []
cnt=0
for file in glob.glob('/home/meiyih/Pytorch-UNet_run1/inference_output_on_ch4_low_light_test_images/'+"*.jpg"):
    in_fn = file
    print('in_fn is ',in_fn)
    fn_idx = in_fn.split('/')[-1]
    print(fn_idx)
    gt_fn = gt_dir + str(fn_idx)
    print(gt_fn)

    in_img = cv2.imread(in_fn)
    gt_img = cv2.imread(gt_fn)
    cnt+=1

    psnrs.append(peak_signal_noise_ratio(gt_img, in_img))
    ssims.append(structural_similarity(gt_img, in_img, multichannel=True))

print(np.mean(psnrs))
print(np.mean(ssims))
print('cnt is',cnt)

in_fn is  /home/meiyih/Pytorch-UNet_run1/inference_output_on_ch4_low_light_test_images/img_292.jpg
img_292.jpg
./ch4_test_images/img_292.jpg
in_fn is  /home/meiyih/Pytorch-UNet_run1/inference_output_on_ch4_low_light_test_images/img_171.jpg
img_171.jpg
./ch4_test_images/img_171.jpg
in_fn is  /home/meiyih/Pytorch-UNet_run1/inference_output_on_ch4_low_light_test_images/img_63.jpg
img_63.jpg
./ch4_test_images/img_63.jpg
in_fn is  /home/meiyih/Pytorch-UNet_run1/inference_output_on_ch4_low_light_test_images/img_417.jpg
img_417.jpg
./ch4_test_images/img_417.jpg
in_fn is  /home/meiyih/Pytorch-UNet_run1/inference_output_on_ch4_low_light_test_images/img_65.jpg
img_65.jpg
./ch4_test_images/img_65.jpg
in_fn is  /home/meiyih/Pytorch-UNet_run1/inference_output_on_ch4_low_light_test_images/img_145.jpg
img_145.jpg
./ch4_test_images/img_145.jpg
in_fn is  /home/meiyih/Pytorch-UNet_run1/inference_output_on_ch4_low_light_test_images/img_151.jpg
img_151.jpg
./ch4_test_images/img_151.jpg
in_fn is  /home/mei